GET http://localhost:5000/infos

###

GET http://localhost:5000/infos/621809de9ba840e03e5ffe80


###


POST http://localhost:5000/infos
Content-Type: application/json

{
    "name": "John",
    "color": "blue"
}


###

DELETE http://localhost:5000/infos/621809de9ba840e03e5ffe80

###

PATCH http://localhost:5000/infos/621809de9ba840e03e5ffe80
Content-Type: application/json

{
    "name": "New Name"
}